
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                yy_size_t yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 153
#define YY_END_OF_BUFFER 154
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[535] =
    {   0,
        0,    0,  154,  152,   12,   11,   45,  152,  152,   36,
       39,  152,   23,   24,   34,   32,   76,   33,   30,   35,
      145,  145,   26,   25,   48,   47,   49,   28,  142,  142,
       19,   21,   37,  142,  142,  142,  142,  142,  142,  142,
      142,  142,  142,  142,  142,  142,  142,  142,  142,  142,
      142,  142,  142,   15,   41,   17,   43,   12,   66,    0,
      150,    0,    0,   54,   18,   70,   57,    0,  148,    0,
       52,   74,   50,   75,   51,   78,   31,    0,  146,   13,
       14,   53,  146,  145,    0,  145,  145,    0,   29,   22,
       16,   20,   61,   68,   65,   69,   62,  142,    0,    0,

       55,  142,  142,  142,  142,  142,  142,  142,  142,  142,
      142,  142,   92,  142,  142,  142,  142,  142,  142,  142,
      142,  142,  105,  142,  142,  142,  142,  142,  142,  142,
      142,   73,  142,  142,  142,  142,  142,  142,  142,  142,
      142,  142,  142,  142,  142,  142,  142,  142,  142,  142,
       59,   72,    0,  150,    0,    0,    0,  148,    0,   77,
       27,    0,  146,    0,  147,  145,  145,  143,   63,   64,
        0,  151,    0,    0,  149,    0,   71,   79,  142,  142,
      142,  142,  142,  142,  142,  142,  142,  142,  142,  142,
      142,  142,  142,  142,  142,  142,  142,  142,  102,  142,

      142,  142,  107,  142,  142,  142,  142,  111,   46,  142,
      142,  142,  142,  142,  142,  142,  142,  142,  142,  142,
      142,  142,  142,  142,  142,  142,  142,  130,  142,  142,
      142,  142,  142,  142,  142,  142,  142,   38,    0,    0,
      146,  147,  143,  143,    0,  151,    0,    0,  149,    0,
      142,   80,  142,  142,   81,  142,   83,  142,   85,  142,
      142,  142,  142,  142,  142,  142,  142,   95,   96,  142,
      142,  142,  142,  142,  142,  104,  142,  108,  142,  142,
      142,  142,  142,  142,  142,  142,  142,  142,  142,  142,
      142,  142,  142,  142,  142,  142,  142,  142,  127,  142,

      129,  142,  142,  142,  142,  142,  138,  142,  142,  142,
      142,    0,  143,  143,  142,  142,   42,   82,   84,   86,
       44,   87,  142,  142,  142,  142,  142,  142,  142,  142,
      100,  101,  142,  142,  142,  142,  142,  142,  142,  142,
       60,  142,  142,  142,  142,  142,  142,  119,  142,  142,
      142,  142,  142,  142,  128,  142,  142,  142,  134,  142,
      136,  142,  142,  142,  141,  142,    0,   58,   40,  142,
      142,  142,   91,   93,  142,  142,   98,   99,  103,  106,
      142,  142,   67,  142,  142,  142,  115,  142,  142,  118,
      120,  121,  122,  124,  125,  142,  142,  132,  142,  142,

        0,  142,  142,  142,   56,    0,  142,  142,   90,  142,
      142,  109,  142,  142,  113,  142,  142,  142,  142,  142,
      131,  142,  142,    0,  137,  142,  140,    0,  142,   89,
      142,   97,  142,  112,  142,  116,  142,  142,  126,  133,
      135,    0,  139,    0,    0,  142,  142,  110,  114,  142,
      142,    0,    0,    0,    0,   88,  142,  142,  142,    0,
        0,    0,    0,    0,    9,  142,  142,  123,    0,    0,
        0,    0,    0,    0,    0,   94,  142,    0,    0,    0,
        0,    0,    0,    0,    0,  142,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  142,    0,    0,    0,    0,

        0,    0,    0,    0,    0,  142,    0,    4,    0,    0,
        2,    0,    0,    0,    0,  117,    0,    0,    0,    0,
        0,    0,    8,    0,    5,    6,    7,    3,    0,    0,
        1,    0,   10,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   28,   28,   28,   29,   30,
       31,   31,   31,   31,   31,   32,   31,   31,   31,   31,
       31,   31,   31,   31,   33,   31,   31,   34,   31,   31,
       35,   36,   37,   38,   39,    1,   40,   41,   42,   43,

       44,   45,   46,   47,   48,   31,   49,   50,   51,   52,
       53,   54,   55,   56,   57,   58,   59,   60,   61,   62,
       63,   64,   65,   66,   67,   68,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[69] =
    {   0,
        1,    1,    1,    1,    1,    2,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    3,
        3,    1,    1,    1,    1,    1,    1,    3,    3,    3,
        4,    4,    4,    4,    1,    2,    1,    1,    4,    3,
        3,    3,    3,    3,    3,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[546] =
    {   0,
        0,    0,  700,  701,   67,  701,  674,   64,  650,   47,
       65,   65,  701,  701,  672,   62,  701,   63,   64,   73,
       85,   92,   56,  701,   72,  671,   67,  701,    0,   89,
      701,  701,  670,   51,   67,   87,   63,   81,   99,  641,
       93,  640,  633,  113,   74,  100,  647,  113,  120,   89,
      110,  123,  637,  701,  123,  701,  701,  171,  701,  144,
      701,  166,  637,  701,  701,  701,  701,  152,  701,  174,
      701,  701,  701,  701,  701,  675,  701,  670,  171,  701,
      701,  701,  175,  207,  192,  164,  136,    0,  701,  701,
      701,  701,  661,  701,  701,  701,  660,    0,  173,  207,

      701,  641,  632,  624,  623,  627,  635,  124,  638,  637,
      147,  184,  617,  623,  617,  614,  160,  622,  618,  614,
      621,  610,    0,  135,  615,  608,  211,  614,  603,  605,
      618,  622,  184,  619,  187,  606,  192,  202,  610,  606,
      193,  185,  602,  130,  607,  598,  202,  606,  604,  595,
      701,  701,  240,  241,  256,  608,  243,  244,  257,  701,
      701,  249,  701,  252,  264,  701,  701,  249,  701,  701,
      255,  701,  283,  254,  701,  285,  610,    0,  595,  234,
      597,  606,  601,  602,  587,  585,  587,  240,  600,  595,
      597,  597,  592,  584,  225,  590,  576,  592,    0,  587,

      577,  581,    0,  582,  587,  283,  582,    0,  586,  568,
      579,  562,  563,  570,  571,  566,  558,  560,  563,  570,
      555,  553,  553,  556,  552,  555,  563,    0,  562,  552,
      556,  551,  544,  558,  560,  559,  548,  558,  546,  285,
      304,  701,  267,  278,  295,  301,  314,  302,  303,  308,
      551,    0,  542,  537,    0,  543,    0,  544,    0,  533,
      539,  530,  539,  527,  527,  534,  532,    0,    0,  534,
      525,  524,  535,  520,  525,    0,  524,    0,  534,  289,
      295,  517,  529,  532,  516,  530,  525,  520,  510,  508,
      509,  506,  519,  509,  513,  518,  517,  508,    0,  496,

        0,  303,  504,  509,  508,  494,    0,  494,  495,  506,
      505,  489,  701,  701,  492,  503,    0,    0,    0,    0,
        0,  506,  492,  493,  498,  497,  492,  497,  480,  485,
        0,    0,  493,  491,  484,    0,    0,  479,  477,  473,
        0,  472,  487,  486,  469,  482,  473,    0,  481,  478,
      480,  463,  473,  479,    0,  474,  474,  476,    0,  463,
      510,  473,  464,  472,    0,  455,  466,    0,    0,  466,
      448,  448,    0,    0,  463,  456,    0,    0,    0,    0,
      459,  462,    0,  448,  456,  441,    0,  454,  441,    0,
        0,    0,  457,    0,    0,  437,  449,    0,  442,  448,

      439,  440,  439,  430,    0,  443,  446,  441,    0,  445,
      425,    0,  440,  425,    0,  436,  423,  424,  435,  432,
        0,  431,  431,  433,    0,  428,    0,  326,  414,    0,
      428,    0,  425,    0,  425,    0,  411,  426,    0,    0,
        0,  414,    0,  337,    0,  406,  423,    0,    0,  418,
      404,  416,  352,  315,  453,    0,  401,  399,  398,  398,
      308,  397,  400,  394,  701,  393,  411,    0,  395,  408,
      389,  398,  387,  278,  388,    0,  401,  402,  383,  297,
      389,  383,  398,  379,  388,  395,  392,  386,  382,  383,
      386,  385,  376,  371,  374,  368,  380,  397,  374,  369,

      394,  379,  370,  373,  370,  357,  410,  701,  372,  366,
      701,  360,  354,  331,  344,    0,  312,  342,  341,  338,
      336,  301,  701,  289,  701,  701,  701,  701,  229,  179,
      701,  131,  701,  701,  372,  376,  378,  382,  386,  119,
      390,  394,  398,  402,  406
    } ;

static yyconst flex_int16_t yy_def[546] =
    {   0,
      534,    1,  534,  534,  534,  534,  534,  535,  534,  534,
      534,  536,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  537,  537,
      534,  534,  534,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  534,  534,  534,  534,  534,  534,  535,
      534,  538,  534,  534,  534,  534,  534,  536,  534,  539,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  540,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  537,  541,  542,

      534,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      534,  534,  535,  535,  538,  534,  536,  536,  539,  534,
      534,  534,  534,  534,  534,  534,  534,  540,  534,  534,
      541,  534,  543,  542,  534,  544,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,

      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  534,  534,
      534,  534,  534,  534,  541,  541,  543,  542,  542,  544,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,

      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  534,  534,  534,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  534,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,

      534,  537,  537,  537,  537,  534,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  534,  537,  537,  537,  534,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  534,  537,  534,  545,  537,  537,  537,  537,  537,
      537,  534,  534,  534,  545,  537,  537,  537,  537,  534,
      534,  534,  534,  534,  534,  537,  537,  537,  534,  534,
      534,  534,  534,  534,  534,  537,  537,  534,  534,  534,
      534,  534,  534,  534,  534,  537,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  537,  534,  534,  534,  534,

      534,  534,  534,  534,  534,  537,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  537,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,    0,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534
    } ;

static yyconst flex_int16_t yy_nxt[770] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       22,   23,   24,   25,   26,   27,   28,   29,   29,   29,
       29,   30,   29,   29,   31,    4,   32,   33,   29,   34,
       35,   36,   37,   38,   39,   40,   29,   41,   29,   42,
       43,   44,   45,   46,   29,   47,   48,   49,   50,   51,
       52,   53,   29,   29,   54,   55,   56,   57,   58,   61,
       58,   64,   65,   66,   69,   72,   77,   89,   74,   91,
       78,   90,   79,   79,   79,   80,   73,   75,   76,   67,
       81,   96,   97,   92,   99,   93,   94,   82,  100,   62,

       70,   83,  102,   84,   84,   84,  112,  103,   83,  104,
       84,   84,   84,   85,  105,  113,   86,   87,   88,  106,
       85,  168,  107,   86,   87,  114,  108,  131,   85,  132,
      115,  127,  116,  109,   86,   85,  110,  123,  118,  111,
      144,   86,  117,   87,  124,  145,   88,  151,  119,   61,
       87,  120,  128,  533,  121,  133,  129,  146,  134,  136,
      137,   69,  147,  140,  148,  130,  141,  167,   60,  149,
      138,  154,   58,  139,   58,  142,   68,  230,  172,   62,
      183,  184,  143,  158,  202,  167,  231,   70,  152,   79,
       79,   79,  203,   79,   79,   79,  166,  187,  188,  162,

      163,  155,  163,  162,  163,  164,  163,  164,  173,  159,
      165,  165,  165,  195,  162,  163,  175,  196,  162,  163,
      163,  532,  166,   83,  163,   84,   84,   84,  189,  206,
      206,  212,  215,  190,  216,   85,  213,  219,   86,   87,
      225,  221,  176,  227,  217,   61,   61,  228,  226,  234,
       85,  235,   69,   69,  531,  220,   86,  222,   60,   68,
      172,  154,  240,  175,  240,   87,  158,  241,  241,  241,
      165,  165,  165,  253,  270,   62,   62,  271,   70,   70,
      243,  244,  165,  165,  165,  171,  254,  174,  246,  176,
      173,  155,  159,  242,  249,  242,  262,  263,  243,  313,

      172,  206,  206,  241,  241,  241,  172,  244,  242,  314,
      174,  175,  175,  242,  280,  281,  171,  249,  247,  246,
      250,  336,  241,  241,  241,  313,  337,  314,  483,  444,
      173,  445,  280,  163,  484,  163,  173,  176,  176,  489,
      453,  281,  445,  250,  337,  356,  530,  336,  163,  247,
      357,  529,  490,  163,  358,  453,  461,  445,  470,  462,
      454,  528,  463,  527,  471,  472,  526,  525,  524,  523,
      522,  464,   60,   60,   60,   60,   68,   68,   68,   68,
       98,   98,  153,  153,  153,  153,  157,  157,  157,  157,
      171,  171,  171,  171,  174,  174,  174,  174,  245,  245,

      245,  245,  248,  248,  248,  248,  455,  521,  455,  455,
      520,  519,  518,  517,  516,  515,  514,  513,  512,  511,
      510,  509,  508,  507,  506,  505,  504,  503,  502,  501,
      500,  499,  498,  497,  496,  495,  494,  493,  492,  491,
      488,  487,  486,  485,  482,  481,  480,  479,  478,  477,
      476,  475,  474,  473,  469,  468,  467,  466,  465,  460,
      459,  458,  457,  456,  452,  451,  450,  449,  448,  447,
      446,  443,  442,  441,  440,  439,  438,  437,  436,  435,
      434,  433,  432,  431,  430,  429,  428,  427,  426,  425,
      424,  423,  422,  421,  420,  419,  418,  417,  416,  415,

      414,  413,  412,  411,  410,  409,  408,  407,  406,  405,
      404,  403,  402,  401,  400,  399,  398,  397,  396,  395,
      394,  393,  392,  391,  390,  389,  388,  387,  386,  385,
      384,  383,  382,  381,  380,  379,  378,  377,  376,  375,
      374,  373,  372,  371,  370,  369,  368,  367,  366,  365,
      364,  363,  362,  361,  360,  359,  355,  354,  353,  352,
      351,  350,  349,  348,  347,  346,  345,  344,  343,  342,
      341,  340,  339,  338,  335,  334,  333,  332,  331,  330,
      329,  328,  327,  326,  325,  324,  323,  322,  321,  320,
      319,  318,  317,  316,  315,  312,  311,  310,  309,  308,

      307,  306,  305,  304,  303,  302,  301,  300,  299,  298,
      297,  296,  295,  294,  293,  292,  291,  290,  289,  288,
      287,  286,  285,  284,  283,  282,  279,  278,  277,  276,
      275,  274,  273,  272,  269,  268,  267,  266,  265,  264,
      261,  260,  259,  258,  257,  256,  255,  252,  251,  239,
      238,  237,  236,  233,  232,  229,  224,  223,  218,  214,
      211,  210,  209,  208,  207,  205,  204,  201,  200,  199,
      198,  197,  194,  193,  192,  191,  186,  185,  182,  181,
      180,  179,  178,  177,  170,  169,  161,  160,  156,  150,
      135,  126,  125,  122,  101,   95,   71,   63,   59,  534,

        3,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534
    } ;

static yyconst flex_int16_t yy_chk[770] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    5,    8,
        5,   10,   10,   11,   12,   16,   19,   23,   18,   25,
       19,   23,   19,   19,   19,   20,   16,   18,   18,   11,
       20,   27,   27,   25,   30,   25,   25,   20,   30,    8,

       12,   21,   34,   21,   21,   21,   37,   34,   22,   34,
       22,   22,   22,   21,   35,   37,   21,   21,   21,   35,
       22,  540,   35,   22,   22,   37,   36,   45,   21,   45,
       38,   44,   38,   36,   21,   22,   36,   41,   39,   36,
       50,   22,   38,   21,   41,   50,   21,   55,   39,   60,
       22,   39,   44,  532,   39,   46,   44,   51,   46,   48,
       48,   68,   51,   49,   52,   44,   49,   87,   62,   52,
       48,   62,   58,   48,   58,   49,   70,  144,   99,   60,
      108,  108,   49,   70,  124,   87,  144,   68,   55,   79,
       79,   79,  124,   83,   83,   83,   86,  111,  111,   79,

       79,   62,   79,   83,   83,   85,   83,   85,   99,   70,
       85,   85,   85,  117,   79,   79,  100,  117,   83,   83,
       79,  530,   86,   84,   83,   84,   84,   84,  112,  127,
      127,  133,  135,  112,  135,   84,  133,  137,   84,   84,
      141,  138,  100,  142,  135,  153,  154,  142,  141,  147,
       84,  147,  157,  158,  529,  137,   84,  138,  155,  159,
      171,  155,  162,  174,  162,   84,  159,  162,  162,  162,
      164,  164,  164,  180,  195,  153,  154,  195,  157,  158,
      168,  168,  165,  165,  165,  173,  180,  176,  173,  174,
      171,  155,  159,  165,  176,  165,  188,  188,  168,  243,

      245,  206,  206,  240,  240,  240,  246,  168,  165,  244,
      250,  248,  249,  165,  206,  206,  247,  250,  173,  247,
      176,  280,  241,  241,  241,  243,  281,  244,  474,  428,
      245,  428,  206,  241,  474,  241,  246,  248,  249,  480,
      444,  206,  444,  250,  281,  302,  524,  280,  241,  247,
      302,  522,  480,  241,  302,  453,  454,  453,  461,  454,
      444,  521,  454,  520,  461,  461,  519,  518,  517,  515,
      514,  454,  535,  535,  535,  535,  536,  536,  536,  536,
      537,  537,  538,  538,  538,  538,  539,  539,  539,  539,
      541,  541,  541,  541,  542,  542,  542,  542,  543,  543,

      543,  543,  544,  544,  544,  544,  545,  513,  545,  545,
      512,  510,  509,  507,  506,  505,  504,  503,  502,  501,
      500,  499,  498,  497,  496,  495,  494,  493,  492,  491,
      490,  489,  488,  487,  486,  485,  484,  483,  482,  481,
      479,  478,  477,  475,  473,  472,  471,  470,  469,  467,
      466,  464,  463,  462,  460,  459,  458,  457,  455,  452,
      451,  450,  447,  446,  442,  438,  437,  435,  433,  431,
      429,  426,  424,  423,  422,  420,  419,  418,  417,  416,
      414,  413,  411,  410,  408,  407,  406,  404,  403,  402,
      401,  400,  399,  397,  396,  393,  389,  388,  386,  385,

      384,  382,  381,  376,  375,  372,  371,  370,  367,  366,
      364,  363,  362,  361,  360,  358,  357,  356,  354,  353,
      352,  351,  350,  349,  347,  346,  345,  344,  343,  342,
      340,  339,  338,  335,  334,  333,  330,  329,  328,  327,
      326,  325,  324,  323,  322,  316,  315,  312,  311,  310,
      309,  308,  306,  305,  304,  303,  300,  298,  297,  296,
      295,  294,  293,  292,  291,  290,  289,  288,  287,  286,
      285,  284,  283,  282,  279,  277,  275,  274,  273,  272,
      271,  270,  267,  266,  265,  264,  263,  262,  261,  260,
      258,  256,  254,  253,  251,  239,  238,  237,  236,  235,

      234,  233,  232,  231,  230,  229,  227,  226,  225,  224,
      223,  222,  221,  220,  219,  218,  217,  216,  215,  214,
      213,  212,  211,  210,  209,  207,  205,  204,  202,  201,
      200,  198,  197,  196,  194,  193,  192,  191,  190,  189,
      187,  186,  185,  184,  183,  182,  181,  179,  177,  156,
      150,  149,  148,  146,  145,  143,  140,  139,  136,  134,
      132,  131,  130,  129,  128,  126,  125,  122,  121,  120,
      119,  118,  116,  115,  114,  113,  110,  109,  107,  106,
      105,  104,  103,  102,   97,   93,   78,   76,   63,   53,
       47,   43,   42,   40,   33,   26,   15,    9,    7,    3,

      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[154] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "120lex.l"
/*	$Id: lexer.l,v 1.2 1997/11/19 15:13:15 sandro Exp $	*/
/*
 * Copyright (c) 1997 Sandro Sigala <ssigala@globalnet.it>.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
/*
 * ISO C++ lexical analyzer.
 *
 * Based on the ISO C++ draft standard of December '96.
 */
#line 35 "120lex.l"
#include <ctype.h>
#include <stdio.h>
#include <stdbool.h>
#include "120gram.tab.h"
#include "token.h"
#include "tlist.h"
#include "tree.h"
#include "symtab.h"

int lineno;

static void skip_until_eol(void);
static void skip_comment(void);
static int check_identifier( char * , tableptr );

//int typenametable_insert(char*, int);
void typenametable_insert( treeptr, tableptr );

/* extern */
extern int yychar;
extern FILE *yyin;
extern nodeptr filestack;
extern YYSTYPE yylval;
extern tableptr classtable;

/* Global variables */

tokenptr yytoken;
int errors = 0;

/* #include flags */
int ctime = 0;
int iostream = 0;
int iomanip = 0;
int cmath = 0;
int cstdlib = 0;
int cstring = 0;
int fstream = 0;
int string = 0;
int usingnamespacestd = 0;

int tokenize(int);
void handle_include();
/* lexer options */
#line 901 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 93 "120lex.l"

#line 1085 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 535 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 701 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 94 "120lex.l"
{ iostream = 1;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 95 "120lex.l"
{ ctime = 1; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 96 "120lex.l"
{ iomanip = 1; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 97 "120lex.l"
{ cmath = 1; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 98 "120lex.l"
{ cstdlib = 1; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 99 "120lex.l"
{ cstring = 1; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 100 "120lex.l"
{ fstream = 1; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 101 "120lex.l"
{ string  = 1; }
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 102 "120lex.l"
{handle_include(); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 103 "120lex.l"
{ usingnamespacestd = 1; }
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 104 "120lex.l"
{ ++lineno; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 105 "120lex.l"
{ /* Ignore whitespace. */ }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 107 "120lex.l"
{ skip_comment(); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 108 "120lex.l"
{ skip_until_eol(); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 110 "120lex.l"
{ return tokenize('{'); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 111 "120lex.l"
{ return tokenize('{'); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 112 "120lex.l"
{ return tokenize('}'); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 113 "120lex.l"
{ return tokenize('}'); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 114 "120lex.l"
{ return tokenize('['); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 115 "120lex.l"
{ return tokenize('['); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 116 "120lex.l"
{ return tokenize(']'); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 117 "120lex.l"
{ return tokenize(']'); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 118 "120lex.l"
{ return tokenize('('); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 119 "120lex.l"
{ return tokenize(')'); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 120 "120lex.l"
{ return tokenize(';'); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 121 "120lex.l"
{ return tokenize(':'); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 122 "120lex.l"
{ return tokenize(ELLIPSIS); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 123 "120lex.l"
{ return tokenize('?'); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 124 "120lex.l"
{ return tokenize(COLONCOLON); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 125 "120lex.l"
{ return tokenize('.'); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 126 "120lex.l"
{ return tokenize(DOTSTAR); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 127 "120lex.l"
{ return tokenize('+'); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 128 "120lex.l"
{ return tokenize('-'); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 129 "120lex.l"
{ return tokenize('*'); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 130 "120lex.l"
{ return tokenize('/'); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 131 "120lex.l"
{ return tokenize('%'); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 132 "120lex.l"
{ return tokenize('^'); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 133 "120lex.l"
{ return tokenize('^'); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 134 "120lex.l"
{ return tokenize('&'); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 135 "120lex.l"
{ return tokenize('&'); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 136 "120lex.l"
{ return tokenize('|'); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 137 "120lex.l"
{ return tokenize('|'); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 138 "120lex.l"
{ return tokenize('~'); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 139 "120lex.l"
{ return tokenize('~'); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 140 "120lex.l"
{ return tokenize('!'); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 141 "120lex.l"
{ return tokenize('!'); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 142 "120lex.l"
{ return tokenize('='); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 143 "120lex.l"
{ return tokenize('<'); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 144 "120lex.l"
{ return tokenize('>'); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 145 "120lex.l"
{ return tokenize(ADDEQ); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 146 "120lex.l"
{ return tokenize(SUBEQ); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 147 "120lex.l"
{ return tokenize(MULEQ); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 148 "120lex.l"
{ return tokenize(DIVEQ); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 149 "120lex.l"
{ return tokenize(MODEQ); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 150 "120lex.l"
{ return tokenize(XOREQ); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 151 "120lex.l"
{ return tokenize(XOREQ); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 152 "120lex.l"
{ return tokenize(ANDEQ); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 153 "120lex.l"
{ return tokenize(ANDEQ); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 154 "120lex.l"
{ return tokenize(OREQ); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 155 "120lex.l"
{ return tokenize(OREQ); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 156 "120lex.l"
{ return tokenize(SL); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 157 "120lex.l"
{ return tokenize(SR); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 158 "120lex.l"
{ return tokenize(SLEQ); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 159 "120lex.l"
{ return tokenize(SREQ); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 160 "120lex.l"
{ return tokenize(EQ); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 161 "120lex.l"
{ return tokenize(NOTEQ); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 162 "120lex.l"
{ return tokenize(NOTEQ); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 163 "120lex.l"
{ return tokenize(LTEQ); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 164 "120lex.l"
{ return tokenize(GTEQ); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 165 "120lex.l"
{ return tokenize(ANDAND); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 166 "120lex.l"
{ return tokenize(ANDAND); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 167 "120lex.l"
{ return tokenize(OROR); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 168 "120lex.l"
{ return tokenize(OROR); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 169 "120lex.l"
{ return tokenize(PLUSPLUS); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 170 "120lex.l"
{ return tokenize(MINUSMINUS); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 171 "120lex.l"
{ return tokenize(','); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 172 "120lex.l"
{ return tokenize(ARROWSTAR); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 173 "120lex.l"
{ return tokenize(ARROW); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 175 "120lex.l"
{ return tokenize(ASM); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 176 "120lex.l"
{ return tokenize(AUTO); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 177 "120lex.l"
{ return tokenize(BOOL); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 178 "120lex.l"
{ return tokenize(BREAK); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 179 "120lex.l"
{ return tokenize(CASE); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 180 "120lex.l"
{ return tokenize(CATCH); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 181 "120lex.l"
{ return tokenize(CHAR); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 182 "120lex.l"
{ return tokenize(CLASS); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 183 "120lex.l"
{ return tokenize(CONST); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 184 "120lex.l"
{ return tokenize(CONST_CAST); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 185 "120lex.l"
{ return tokenize(CONTINUE); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 186 "120lex.l"
{ return tokenize(DEFAULT); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 187 "120lex.l"
{ return tokenize(DELETE); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 188 "120lex.l"
{ return tokenize(DO); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 189 "120lex.l"
{ return tokenize(DOUBLE); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 190 "120lex.l"
{ return tokenize(DYNAMIC_CAST); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 191 "120lex.l"
{ return tokenize(ELSE); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 192 "120lex.l"
{ return tokenize(ENUM); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 193 "120lex.l"
{ return tokenize(EXPLICIT); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 194 "120lex.l"
{ return tokenize(EXPORT); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 195 "120lex.l"
{ return tokenize(EXTERN); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 196 "120lex.l"
{ return tokenize(FALSE); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 197 "120lex.l"
{ return tokenize(FLOAT); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 198 "120lex.l"
{ return tokenize(FOR); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 199 "120lex.l"
{ return tokenize(FRIEND); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 200 "120lex.l"
{ return tokenize(GOTO); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 201 "120lex.l"
{ return tokenize(IF); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 202 "120lex.l"
{ return tokenize(INLINE); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 203 "120lex.l"
{ return tokenize(INT); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 204 "120lex.l"
{ return tokenize(LONG); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 205 "120lex.l"
{ return tokenize(MUTABLE); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 206 "120lex.l"
{ return tokenize(NAMESPACE); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 207 "120lex.l"
{ return tokenize(NEW); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 208 "120lex.l"
{ return tokenize(OPERATOR); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 209 "120lex.l"
{ return tokenize(PRIVATE); }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 210 "120lex.l"
{ return tokenize(PROTECTED); }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 211 "120lex.l"
{ return tokenize(PUBLIC); }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 212 "120lex.l"
{ return tokenize(REGISTER); }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 213 "120lex.l"
{ return tokenize(REINTERPRET_CAST); }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 214 "120lex.l"
{ return tokenize(RETURN); }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 215 "120lex.l"
{ return tokenize(SHORT); }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 216 "120lex.l"
{ return tokenize(SIGNED); }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 217 "120lex.l"
{ return tokenize(SIZEOF); }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 218 "120lex.l"
{ return tokenize(STATIC); }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 219 "120lex.l"
{ return tokenize(STATIC_CAST); }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 220 "120lex.l"
{ return tokenize(STRUCT); }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 221 "120lex.l"
{ return tokenize(SWITCH); }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 222 "120lex.l"
{ return tokenize(TEMPLATE); }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 223 "120lex.l"
{ return tokenize(THIS); }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 224 "120lex.l"
{ return tokenize(THROW); }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 225 "120lex.l"
{ return tokenize(TRUE); }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 226 "120lex.l"
{ return tokenize(TRY); }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 227 "120lex.l"
{ return tokenize(TYPEDEF); }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 228 "120lex.l"
{ return tokenize(TYPEID); }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 229 "120lex.l"
{ return tokenize(TYPENAME); }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 230 "120lex.l"
{ return tokenize(UNION); }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 231 "120lex.l"
{ return tokenize(UNSIGNED); }
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 232 "120lex.l"
{ return tokenize(USING); }
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 233 "120lex.l"
{ return tokenize(VIRTUAL); }
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 234 "120lex.l"
{ return tokenize(VOID); }
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 235 "120lex.l"
{ return tokenize(VOLATILE); }
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 236 "120lex.l"
{ return tokenize(WCHAR_T); }
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 237 "120lex.l"
{ return tokenize(WHILE); }
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 239 "120lex.l"
{ return tokenize( check_identifier(yytext, classtable) ); }
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 241 "120lex.l"
{ return tokenize(INTEGER); }
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 242 "120lex.l"
{ return tokenize(INTEGER); }
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 243 "120lex.l"
{ return tokenize(INTEGER); }
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 245 "120lex.l"
{ return tokenize(FLOATING); }
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 246 "120lex.l"
{ return tokenize(FLOATING); }
	YY_BREAK
case 148:
/* rule 148 can match eol */
YY_RULE_SETUP
#line 248 "120lex.l"
{ return tokenize(CHARACTER); }
	YY_BREAK
case 149:
/* rule 149 can match eol */
YY_RULE_SETUP
#line 249 "120lex.l"
{ return tokenize(CHARACTER); }
	YY_BREAK
case 150:
/* rule 150 can match eol */
YY_RULE_SETUP
#line 251 "120lex.l"
{ return tokenize(STRING); }
	YY_BREAK
case 151:
/* rule 151 can match eol */
YY_RULE_SETUP
#line 252 "120lex.l"
{ return tokenize(STRING); }
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 254 "120lex.l"
{ fprintf(stderr, "%d: unexpected character `%c'\n", lineno, yytext[0]); }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 256 "120lex.l"
{ 

  yypop_buffer_state();
  pop_node(&filestack);
  if (filestack == NULL) {
    yyterminate();    
    printf("ALL FILES PARSED!\n");
  }

  yylineno = 1;
  if (!YY_CURRENT_BUFFER) {
    printf("NO MORE BUFFERS!\n");
    yyterminate();
  } 
}
	YY_BREAK
case 153:
YY_RULE_SETUP
#line 272 "120lex.l"
ECHO;
	YY_BREAK
#line 1967 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 535 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 535 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 534);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 272 "120lex.l"



int tokenize(int category) {
  yytoken = create_token(category, yytext, yylineno, filestack->filename);

  yylval.tptr = alctree(yytext, category, 0);
  yylval.tptr->leaf = yytoken;
  return category;
  
};

/*
 * We use this routine instead a lex pattern because we don't need
 * to save the matched comment in the `yytext' buffer.
 */

static void skip_comment(void) {
	int c1, c2;

	c1 = input();
	c2 = input();

	while (c2 != EOF && !(c1 == '*' && c2 == '/')) {
		if (c1 == '\n')
			++lineno;
		c1 = c2;
		c2 = input();
	}
};

static void skip_until_eol(void) {
	int c;

	while ((c = input()) != EOF && c != '\n')
		;
	++lineno;
};

/* Handles includes using built-in yybuffer */
void handle_include() {

  char *fname = malloc(strlen(yytext)+1-strlen("#include \"\""));
  fname = strchr(yytext, '\"')+1;
  fname[strlen(fname)-1] = '\0';
  printf("%s\n",fname);
  yyin = fopen(fname,"r");
  push_node(&filestack, fname);
  yypush_buffer_state(yy_create_buffer(yyin,YY_BUF_SIZE));

};

/*
 * Type name table.
 * Replace this with a hash table, when you get a chance.
 */

struct typenametable_entry {
   char *name;
   int category;
   struct typenametable_entry *next;
   } *head;


/*
int typenametable_lookup(char *s)
{
   struct typenametable_entry *tmp = head;
   while (tmp) {
      if (!strcmp(s, tmp->name)) return tmp->category;
      tmp = tmp->next;
   }
   return IDENTIFIER;
}
*/

/*
int typenametable_insert(char *s, int cat)
{
   struct typenametable_entry *tmp = head;
   while (tmp) {
      if (!strcmp(s, tmp->name)) {
         fprintf(stderr,
	    "warning, %s is already in the typename table as a %d\n",
	    s, tmp->category );
         return tmp->category;
         }
      tmp = tmp->next;
   }
   tmp = calloc(1, sizeof (struct typenametable_entry));
   if(!tmp) { fprintf(stderr, "tnti out of memory\n"); return -1; }
   tmp->name = strdup(s);
   tmp->category = cat;
   tmp->next = head;
   head = tmp;
};
*/

void classnametable_insert(treeptr tp, tableptr t) {

   /* Checkit */
   if ( lookup( tp->leaf->text , t ) == true) {
        fprintf(stderr,
	    "warning, %s is already in the typename table as a %d\n",
            tp->leaf->text, tp->leaf->category );
   } else {

     insert_entry( tp->leaf->text , t );
     tp->leaf->category = CLASS_NAME;

   }
};


static int check_identifier( char *s , tableptr t ) {


        if ( lookup( s , t ) == true ) {
 
        printf( "\"%s\" is a class member\n", s );
            
            return CLASS_NAME;

         } else {

            return IDENTIFIER;

        }
};

